apiVersion: v1
kind: Pod
metadata:
  name: privileged-alpine
spec:
  containers:
  - name: alpine
    image: public.aws.ecr/docker/library/alpine:3.22
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
