apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    app: nginx
  namespace: default
type: Opaque
data:
  secret.html: "PGh0bWw+PGhlYWQ+PHRpdGxlPlNlY3JldCBQYWdlPC90aXRsZT48L2hlYWQ+PGJvZHk+PGgxPlNlY3JldCBjb250ZW50IGZyb20gU2VjcmV0ITwvaDE+PC9ib2R5PjwvaHRtbD4="
