---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
  namespace: object-store
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      initContainers:
      - name: configure-mc
        image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
        command:
          - /bin/sh
          - -c
          - mc alias set local http://object-store.object-store.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
        envFrom:
        - secretRef:
            name: object-store-env
        volumeMounts:
        - name: mc-config
          mountPath: /root
      containers:
      - name: make-bucket
        image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
        command:
          - /bin/sh
          - -c
          - |
            mc mb --ignore-existing local/k8scourse-private
            mc mb --ignore-existing local/k8scourse-public
            mc anonymous set download local/k8scourse-public
        volumeMounts:
        - name: mc-config
          mountPath: /root
      restartPolicy: Never
      volumes:
      - name: mc-config
        emptyDir: {}
