---
- hosts: k8s-servers
  become: true
  any_errors_fatal: true
  roles:
    - role: api-load-balancer
      tags:
        - 'api-load-balancer'
        - 'setup'

- hosts: k8s-servers,k8s-workers
  become: true
  any_errors_fatal: true
  roles:
    - role: install-cri-o
      tags:
        - cri
        - setup
    - role: install-k8s
      tags:
        - k8s
        - setup

- hosts: k8s-servers,k8s-workers
  become: true
  any_errors_fatal: true
  serial: 1
  roles:
    - role: bootstrap-k8s
      tags:
        - bootstrap

# - hosts: k8s-servers[0]
#   become: true
#   roles:
#     - role: nfs-server

# - hosts: k8s-servers[1:],k8s-workers
#   become: true
#   roles:
#     - role: nfs-client

- hosts: all
  become: true
  roles:
    - role: nfs-server
      when: inventory_hostname == groups['k8s-servers'][0]
      tags:
        - nfs
    - role: nfs-client
      when: inventory_hostname != groups['k8s-servers'][0]
      tags:
        - nfs

- hosts: k8s-servers[0]
  become: true
  roles:
    - role: copy-kubeconfig
      tags:
        - kubeconfig
    - role: services
      tags:
        - services
