FROM public.ecr.aws/docker/library/debian:trixie

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y haproxy

COPY haproxy.cfg /etc/haproxy/haproxy.cfg

ENTRYPOINT [ "/usr/sbin/haproxy", "-db", "-f", "/etc/haproxy/haproxy.cfg" ]
