apiVersion: v1
kind: Pod
metadata:
  name: security-context-alpine
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - name: alpine
    image: public.aws.ecr/docker/library/alpine:3.22
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
