---
- name: Install cert-manager
  kubernetes.core.helm:
    release_name: cert-manager
    release_namespace: cert-manager
    create_namespace: true
    chart_ref: oci://quay.io/jetstack/charts/cert-manager
    chart_version: v1.19.1
    release_values:
      crds:
        enabled: true
  environment:
    K8S_AUTH_KUBECONFIG: /etc/kubernetes/super-admin.conf

- name: Deploy cert-manager issuer
  command:
    cmd: kubectl apply -f -
    stdin: |-
      ---
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned-cluster-issuer
      spec:
        selfSigned: {}
      ---
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: selfsigned-ca
        namespace: cert-manager
      spec:
        isCA: true
        commonName: selfsigned-ca
        secretName: root-secret
        privateKey:
          algorithm: ECDSA
          size: 256
        issuerRef:
          name: selfsigned-cluster-issuer
          kind: ClusterIssuer
          group: cert-manager.io
      ---
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: ca-issuer
      spec:
        ca:
          secretName: root-secret
  environment:
    KUBECONFIG: /etc/kubernetes/super-admin.conf
  register: cert_manager_result
  until: cert_manager_result is succeeded
  retries: 180
  delay: 1