---
- name: Deploy NGINX Ingress Controller
  kubernetes.core.helm:
    release_name: ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_ref: ingress-nginx
    chart_version: 4.13.3
    release_values:
      controller:
        ingressClassResource:
          name: nginx
          enabled: true
          default: true
        service:
          enabled: true
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: 172.16.42.142
        admissionWebhooks:
          enabled: false
  environment:
    K8S_AUTH_KUBECONFIG: /etc/kubernetes/super-admin.conf