---
#
# Install Helm
#

- name: Install required packages for Helm installation
  apt:
    name:
      - curl
      - gpg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Add Helm GPG key
  shell: curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/helm.gpg

- name: Add Helm apt repository
  copy:
    dest: /etc/apt/sources.list.d/helm-stable-debian.list
    content: 'deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main'
    owner: root
    group: root
    mode: '0644'
  register: helm_repo

- name: Update apt cache after adding Helm repo
  apt:
    update_cache: yes
  when: helm_repo is changed

- name: Install Helm
  apt:
    name: helm
    state: present

#
# NFS CSI
#

- import_tasks: nfs-csi.yaml

#
# MetalLB
#

- import_tasks: metallb.yaml

#
# NGINX Ingress Controller
#

- import_tasks: ingress-controller.yaml

#
# Cert-Manager
#

- import_tasks: cert-manager.yaml

#
# Container Registry
#

# - name: Deploy container registry
#   command:
#     cmd: kubectl apply -f -
#     stdin: "{{ lookup('file', 'container-registry.yml') }}"
#   environment:
#     KUBECONFIG: /etc/kubernetes/super-admin.conf
