---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      serviceAccountName: prometheus
      initContainers:
      - name: init-chown-data
        image: alpine
        command: ["sh", "-c", "chown -R 65534:65534 /data"]
        volumeMounts:
        - name: storage-volume
          mountPath: /data
      containers:
      - name: prometheus
        image: prometheus
        args:
        - "--config.file=/etc/prometheus.yml"
        - "--storage.tsdb.path=/var/lib/prometheus"
        - "--storage.tsdb.retention.time=24h"
        - "--storage.tsdb.retention.size=1GB"
        - "--web.listen-address=:9090"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus.yml
          readOnly: true
          subPath: prometheus.yml
        - name: storage-volume
          mountPath: /var/lib/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: storage-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
