apiVersion: batch/v1
kind: CronJob
metadata:
  name: alpine-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: alpine-cronjob
        spec:
          containers:
          - name: alpine
            image: public.ecr.aws/docker/library/alpine:3.22
            command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
          restartPolicy: Never
