# Makefile for builtin controllers examples

up-replicaset:
	kubectl apply -f replicaset.yaml

down-replicaset:
	kubectl delete -f replicaset.yaml

up-deployment:
	kubectl apply -f deployment.yaml

down-deployment:
	kubectl delete -f deployment.yaml

up-statefulset:
	kubectl apply -f statefulset.yaml

down-statefulset:
	kubectl delete -f statefulset.yaml

up-daemonset:
	kubectl apply -f daemonset.yaml

down-daemonset:
	kubectl delete -f daemonset.yaml

up-job:
	kubectl apply -f job.yaml

down-job:
	kubectl delete -f job.yaml

up-cronjob:
	kubectl apply -f cronjob.yaml

down-cronjob:
	kubectl delete -f cronjob.yaml
